# -*- coding: utf-8 -*-
"""Walmart_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fA0OMAO3Yh2jSN1vV1-8GOrOyn4nKNe6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"/content/Walmart_Sales.csv")  # Update path and file name

# Check first few rows

df.info()
df.describe()
df.isnull().sum()

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y') # Changed the format to '%d-%m-%Y' to match the actual date format in the data

print("Total Sales:", df['Weekly_Sales'].sum())

print(df.groupby('Store')['Weekly_Sales'].mean().sort_values(ascending=True))

print(df.groupby('Holiday_Flag')['Weekly_Sales'].mean())

"""**Visualizations**
1. Weekly Sales Distribution

"""

sns.histplot(df['Weekly_Sales'],kde=True)
plt.title('Weekly Sales Distribution')
plt.show()

df.groupby('Date')['Weekly_Sales'].sum().plot(figsize=(12,6))
plt.title("Total Weekly Sales Over Time")
plt.ylabel("Sales")
plt.show()

top_stores = df.groupby('Store')['Weekly_Sales'].sum().nlargest(5)
top_stores.plot(kind='bar', color='orange')
plt.title("Top 5 Stores by Total Sales")
plt.ylabel("Sales")
plt.show()

sns.scatterplot(x='Temperature', y='Weekly_Sales', data=df)
plt.title("Temperature vs Weekly Sales")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()